cart/urls.py
from django.urls import path
from .views import cart_add, CartView, cart_remove, change_count


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_pk>/', cart_add, name='random_add'),
    path('add/<int:product_pk>/<int:shop_product_pk>/', cart_add, name='add'),
    path('change/<int:shop_product_pk>/<str:quantity>/', change_count, name='change'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

users/urls.py
from django.urls import path

from users.views import register_view, LogOutView, reset_password, user_login, HistoryView, history_remove

app_name = 'users'


urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('password_reset/', reset_password, name='reset_password'),
    path("history/", HistoryView.as_view(), name='view_history'),
    path("history/remove/<int:pk>", history_remove, name='history_remove')
]

templates/inc/blocks/top_nav_panel_blocks/login.html
{% load i18n %}

<nav class="row-block">
  <div class="row ControlPanel-rowSplit">
    <div class="row-block">
        {% if user.is_authenticated %}
          <a style="margin-right: 20px" class="ControlPanel-title" href="{% url 'account' %}">{% trans 'Личный кабинет' %}</a>
            <a class="ControlPanel-title" href="{% url 'users:logout' %}">{% trans 'Выйти из системы' %}</a>
        {% else %}
            <a class="ControlPanel-title" href="{% url 'users:login' %}">{% trans 'Вход/Регистрация' %}</a>
        {% endif %}
    </div>
  </div>
</nav>