cart/urls.py
from django.urls import path
from .views import cart_add, CartView, cart_remove, change_count


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_pk>/', cart_add, name='random_add'),
    path('add/<int:product_pk>/<int:shop_product_pk>/', cart_add, name='add'),
    path('change/<int:shop_product_pk>/<str:quantity>/', change_count, name='change'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.CatalogView.as_view(), name='catalog'),
    path('order_by_date/', views.CatalogOrderByDateView.as_view(), name='catalog_order_by_date'),
    path('order_by_views/', views.CatalogOrderByViewsView.as_view(), name='catalog_order_by_views'),
    path('order_by_price/', views.CatalogOrderByPriceView.as_view(), name='catalog_order_by_price'),
    path('order_by_rating/', views.CatalogOrderByRatingView.as_view(), name='catalog_order_by_rating'),
    path('category/<slug:slug>/', views.CatalogCategoryView.as_view(), name='catalog_category'),
    path('category_order_by_date/<slug:slug>/', views.CatalogOrderByDateView.as_view(),
         name='catalog_category_order_by_date'),
    path('category_order_by_views/<slug:slug>/', views.CatalogOrderByViewsView.as_view(),
         name='catalog_category_order_by_views'),
    path('category_order_by_price/<slug:slug>/', views.CatalogCategoryOrderByPriceView.as_view(),
         name='catalog_category_order_by_price'),
    path('category_order_by_rating/<slug:slug>/', views.CatalogCategoryOrderByRatingView.as_view(),
         name='catalog_category_order_by_rating'),
    path('add/<int:pk>/', views.CatalogView.add_to_compare, name='add_to_compare')
]

compare/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.CompareView.as_view(), name='compare'),
    path('delete_from_compare/<int:pk>/', views.CompareView.delete_from_compare, name='delete_from_compare'),
]

order/urls.py
from django.urls import path
from .views import OrderHistory, OrderView, StepOne, StepTwo, StepThree, StepFour, PaymentView, PaymentProcess

urlpatterns = [
    path("history/", OrderHistory.as_view(), name="history-order"),
    path("history/<int:order_pk>/", OrderView.as_view(), name="one-order"),
    path("step1/", StepOne.as_view(), name="order-step-one"),
    path("step2/", StepTwo.as_view(), name="order-step-two"),
    path("step3/", StepThree.as_view(), name="order-step-three"),
    path("step4/", StepFour.as_view(), name="order-step-four"),
    path("payment/order/<int:order_pk>/", PaymentView.as_view(), name="payment_order"),
    path("payment/process/<int:order_pk>/", PaymentProcess.as_view(), name="payment_progress"),
]

compare/models.py
# from django.db import models

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    """Форма для добавления товара в корзину"""
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'Amount-input form-input', 'value': 1}))

    def clean_quantity(self):
        """Функция проверяет, что поле является числом"""
        data = self.cleaned_data['quantity']
        try:
            data = int(data)
            return data
        except ValueError:
            pass

order/forms.py
from django import forms
from .models import Order


class StepOneForm(forms.ModelForm):
    class Meta:
        model = Order
        widgets = {
            "first_second_names": forms.TextInput(
                attrs={
                    "class": "form-input border-custom",
                    "placeholder": "Введите имя и фамилию",
                    "required": True,
                }
            ),
            "phone": forms.TextInput(
                attrs={
                    "class": "form-input border-custom",
                    "placeholder": "Введите телефон",
                    "required": True,
                }
            ),
            "email": forms.TextInput(
                attrs={
                    "class": "form-input border-custom",
                    "placeholder": "Введите почту",
                    "required": True,
                }
            ),
        }
        fields = ["first_second_names", "phone", "email"]


class StepTwoForm(forms.ModelForm):
    class Meta:
        model = Order
        widgets = {
            "delivery": forms.RadioSelect(attrs={"class": "toggle-box"}),
            "city": forms.TextInput(attrs={
                "class": "form-input border-custom",
                "placeholder": "Введите город",
                "required": True
                }
            ),
            "address": forms.Textarea(attrs={
                "class": "form-textarea border-custom",
                "placeholder": "Введите адрес",
                "required": True
            }),
        }
        fields = ["delivery", "city", "address"]


class StepThreeForm(forms.ModelForm):
    class Meta:
        model = Order
        widgets = {
            "payment": forms.RadioSelect(attrs={"class": "toggle-box"}),
        }
        fields = [
            "payment",
        ]

product/forms.py
from django import forms
from .models import Review, Product


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "rating"]


class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "slug", "category", "description", "sort_index")

cart/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView

from .services import add_product_to_cart, remove_product, get_form_add_cart, get_product, change_count_cart


class CartView(TemplateView):
    """Представление корзины пользователя"""
    template_name = 'cart.html'


def cart_add(request, product_pk, shop_product_pk=None):
    """Представление добавления товара в корзину"""
    product = get_product(product_pk, 'pk', 'slug')
    form = get_form_add_cart(request)

    if request.method == 'GET' or form.is_valid():
        add_product_to_cart(request, product_pk, shop_product_pk, form)
    return redirect(to='product', slug=product.slug)


def change_count(request, shop_product_pk, quantity):
    """Представления изменения кол-во товара в корзине"""
    change_count_cart(request, shop_product_pk, int(quantity))
    return redirect(to='cart:cart')


def cart_remove(request, pk: int):
    """Представление удаления товара из корзины"""
    remove_product(request, pk)
    return redirect(to='cart:cart')

catalog/views.py
from product.models import Product

from . import services


class CatalogView(services.CatalogProductService):
    """Представление страницы каталога"""
    template_name = 'catalog.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 2


class CatalogOrderByDateView(services.CatalogProductOrderByService, CatalogView):
    """Представление страницы каталога с отсортированными продуктами по дате"""
    field = 'created_at'


class CatalogOrderByViewsView(services.CatalogProductOrderByService, CatalogView):
    """Представление страницы каталога с отсортированными продуктами по просмотрам"""
    field = 'views'


class CatalogOrderByPriceView(services.CatalogProductOrderByService, CatalogView):
    """Представление страницы каталога с отсортированными продуктами по цене"""
    field = 'shop_products__price'


class CatalogOrderByRatingView(services.CatalogProductOrderByService, CatalogView):
    """Представление страницы каталога с отсортированными продуктами по популярности"""
    field = 'reviews__rating'


class CatalogCategoryView(services.CatalogCategoryService):
    """Представление страницы каталога с категорией продуктов"""
    template_name = 'catalog.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 2


class CatalogCategoryOrderByDateView(services.CatalogCategoryOrderByService, CatalogCategoryView):
    """Представление страницы каталога с категорией продуктов отсортированные по дате"""
    field = 'created_at'


class CatalogCategoryOrderByViewsView(services.CatalogCategoryOrderByService, CatalogCategoryView):
    """Представление страницы каталога с категорией продуктов отсортированные по просмотрам"""
    field = 'views'


class CatalogCategoryOrderByPriceView(services.CatalogCategoryOrderByService, CatalogCategoryView):
    """Представление страницы каталога с категорией продуктов отсортированные по цене"""
    field = 'shop_products__price'


class CatalogCategoryOrderByRatingView(services.CatalogCategoryOrderByService, CatalogCategoryView):
    """Представление страницы каталога с категорией продуктов отсортированные по популярности"""
    field = 'reviews__rating'

compare/views.py
from product.models import Product

from . import services


class CompareView(services.CompareServices):
    model = Product
    template_name = 'compare/compare.html'

main_page/views.py
from django.shortcuts import render
from django.views import View
from administration.models import Cache
from .services import MainPage


class MainPageView(View):

    def get(self, request):
        banners = MainPage.get_banners()
        hot_offers = MainPage.get_hot_offers()
        top_products = MainPage.get_top_products()
        favourite_categories = MainPage.get_favourite_categories()
        day_offer = MainPage.get_day_offer()
        limited_offers = MainPage.get_limited_offers()
        try:
            main_cache = Cache.objects.get(name='Main cache')
        except Cache.DoesNotExist:
            main_cache = None
        context = {
            'banners': banners,
            'favourite_categories': favourite_categories,
            'day_offer': day_offer,
            'top_products': top_products,
            'hot_offers': hot_offers,
            'limited_offers': limited_offers,
            'main_cache': main_cache.value if main_cache is not None else main_cache,
        }
        return render(request, 'main_page/main_page.html', context)


class ContactsView(View):
    def get(self, request):
        return render(request, 'main_page/contacts.html')

order/views.py
from django.http import Http404
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import TemplateView, DetailView
import datetime
from cart.services import Cart
from .models import Order, OrderGood
from .forms import StepOneForm, StepTwoForm, StepThreeForm
from cart.models import ProductInCart
from .services import PaymentService


class OrderHistory(View):
    template_name = "order/historyorder.html"

    def get(self, request, *args, **kwargs):
        orders = Order.objects.all().filter(consumer=request.user, order_in=True)
        return render(request, self.template_name, {"orders": orders})


class OrderView(DetailView):
    template_name = "order/order.html"

    def get(self, request, *args, **kwargs):
        goods_in_order = Order.objects.get(pk=kwargs["order_pk"])
        return render(request, self.template_name, {"goods_in_order": goods_in_order})


class StepOne(View):
    template_name = "order/step_one.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            form = StepOneForm
            return render(request, self.template_name, {"form": form})
        else:
            return redirect("users:register")

    def post(self, request, *args, **kwargs):
        form = StepOneForm(request.POST)
        order = Order.objects.create(consumer=request.user, order_in=False)
        q = ProductInCart.objects.filter(user=request.user).select_related("shop_product__product")
        for good in q:
            OrderGood.objects.create(good_in_order=order,
                                     good_in_cart=good.shop_product.product,
                                     amount=good.quantity,
                                     price=good.shop_product.price,
                                     old_price=good.shop_product.old_price)
        if form.is_valid():
            order.first_second_names = form.cleaned_data["first_second_names"]
            order.email = form.cleaned_data["email"]
            order.phone = form.cleaned_data["phone"]
            order.save()
            return redirect("order-step-two")
        return render(request, self.template_name, {"form": form})


class StepTwo(View):
    template_name = "order/step_two.html"

    def get(self, request, *args, **kwargs):
        form = StepTwoForm
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = StepTwoForm(request.POST)
        order = Order.objects.filter(consumer=request.user, order_in=False).first()
        if form.is_valid():
            order.delivery = form.cleaned_data["delivery"]
            order.city = form.cleaned_data["city"]
            order.address = form.cleaned_data["address"]
            order.save()
            return redirect("order-step-three")
        return render(request, self.template_name, {"form": form})


class StepThree(TemplateView):
    template_name = "order/step_three.html"

    def get(self, request, *args, **kwargs):
        form = StepThreeForm
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = StepThreeForm(request.POST)
        order = Order.objects.filter(consumer=request.user, order_in=False).first()
        if form.is_valid():
            order.payment = form.cleaned_data["payment"]
            order.order_in = True
            order.ordered = datetime.datetime.today()
            order.save()
            return redirect("order-step-four")
        return render(request, self.template_name, {"form": form})


class StepFour(View):
    template_name = "order/step_four.html"

    def get(self, request, *args, **kwargs):
        Cart(request).clear()
        order = Order.objects.filter(consumer=request.user, order_in=True).first()
        return render(request, self.template_name, {"order": order})


class PaymentView(View):
    template_name = "payment/payment.html"

    def get(self, request, *args, **kwargs):
        order = Order.objects.get(consumer=request.user, pk=kwargs["order_pk"])
        if order.payment == 'random':
            self.template_name = 'payment/payment_random.html'
        return render(request, self.template_name, {"order": order})

    def post(self, request, order_pk):
        try:
            raw_card_number = request.POST['numero1']
            card_number = int(raw_card_number.replace(' ', ''))
            PaymentService.add_order_to_payment_queue(order_id=order_pk, cart_number=card_number)
            return redirect('payment_progress', order_pk=order_pk)
        except ValueError:
            raise Http404


class PaymentProcess(View):
    template_name = "payment/payment_process.html"

    def get(self, request, *args, **kwargs):
        order = Order.objects.get(pk=kwargs["order_pk"])
        return render(request, self.template_name, {"order": order})

product/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView

from personal_account.services import PersonalAccount
from .models import Product, Review
from .forms import CreateProductForm
from .services import ProductService
from cart.forms import CartAddProductForm


class ProductDetail(DetailView):
    model = Product
    context_object_name = "product"
    template_name = "product/product.html"

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related("reviews__user", "shop_products__store", "images")
        return queryset

    def get_object(self, queryset=None):
        return get_object_or_404(Product, slug=self.kwargs.get("slug"))

    def get_context_data(self, **kwargs):
        context = super(ProductDetail, self).get_context_data(**kwargs)
        context["user_review"] = ProductService.user_has_review(self.request.user, self.object)
        context["form"] = CartAddProductForm()
        reviews = Review.objects.filter(product=self.object)
        paginator = Paginator(reviews, 1)
        page = self.request.GET.get("page")
        context["reviews"] = paginator.get_page(page)
        context["paginator"] = paginator
        return context

    def get(self, request, *args, **kwargs):
        ProductService.views_increment(self)
        PersonalAccount.add_viewed_product(user=request.user.id, product=self.get_object().id)
        return super(ProductDetail, self).get(request, *args, **kwargs)

    def post(self, request, **kwargs):
        self.object = self.get_object()
        ProductService.review_form_save(instance=self, request=request)
        return redirect(reverse(viewname="product", kwargs={"slug": self.kwargs["slug"]}))


class ProductCreateView(ProductService, View):
    template_name = "product/create_product.html"

    def get(self, request):
        form = CreateProductForm()
        categories = self.get_all_categories
        return render(request, self.template_name, {"form": form, "categories": categories})

    def post(self, request):
        form = CreateProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("seller-room"))
        return render(request, self.template_name, {"form": form})

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Megano</title>
  <meta name="description" content="{% translate 'Описание страницы' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
  <link href="{% static 'favicon.ico' %}" rel="shortcut icon">
  {% url 'import_data' as url_import_data %}
  {% if request.path == url_import_data %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  {% endif %}
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff' %}" as="font">
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff' %}" as="font">
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff' %}" as="font">
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff' %}" as="font">
  <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
  <link rel="stylesheet" href="{% static 'assets/css/fonts.css' %}?v=65245665">
  <link rel="stylesheet" href="{% static 'assets/css/basic.css' %}?v=65245665">
  <link rel="stylesheet" href="{% static 'assets/css/extra.css' %}?v=65245665">
  <script src="{% static 'assets/plg/CountDown/countdown.js' %}"></script>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>

{% block header %}
  {% include 'inc/_header.html' %}
{% endblock %}

{% block header_slider %}
{% endblock %}

{% block main %}
{% endblock %}

{% block pagination %}
  {% include 'inc/blocks/pagination.html' %}
{% endblock %}

{% block footer %}
  {% include 'inc/_footer.html' %}
{% endblock %}

{% if request.path == url_import_data %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
{% endif %}
<script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
<script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>
<script src="{% static 'assets/js/openOrders.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block main %}

  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans 'Корзина' %}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main_page' %}">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Корзина' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        {% if cart %}
          <form class="form Cart" action="#" method="post">
            {% for item in cart %}
              {% with product=item.shop_product.product shop=item.shop_product.store shop_product=item.shop_product %}
              <div class="Cart-product">
                <div class="Cart-block Cart-block_row">
                  <div class="Cart-block Cart-block_pict">
                    <a class="Cart-pict" href="{% url 'product' product.slug %}">
                      <img class="Cart-img" src="{{ product.images.all.0 }}" alt="card.jpg"/>
                    </a>
                  </div>
                  <div class="Cart-block Cart-block_info"><a class="Cart-title" href="#">{{ product.name }}</a>
                    <div class="Cart-desc">{{ product.description }}
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_price">
                    {% if shop_product.old_price %}
                      <div class="Cart-price Cart-price_old">{{ shop_product.old_price }}</div>
                    {% endif %}
                    <div class="Cart-price">{{ shop_product.price }}
                    </div>
                  </div>
                </div>
                <div class="Cart-block Cart-block_row">
                  <div class="Cart-block Cart-block_seller">
                    <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                  <div class="form-select">{{ shop.name }}</div>
                  </div>
                  <div class="Cart-block Cart-block_amount">
                    <div class="Cart-amount">
                      <div class="Amount">
                          <a href="{% url 'cart:change' shop_product.id '-1' %}" class="Amount-remove-cart" type="button"></a>
                          <span class="Amount-input form-input">{{ item.quantity }}</span>
                          <a href="{% url 'cart:change' shop_product.id '+1' %}" class="Amount-add-cart" type="button"></a>
                      </div>
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_delete">
                    <a class="Cart-delete" href="{% url 'cart:remove' product.id %}">
                      <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/>
                    </a>
                  </div>
                </div>
              </div>
              {% endwith %}
            {% endfor %}
            <div class="Cart-total">
              <div class="Cart-block Cart-block_total">
                <strong class="Cart-title">{% trans 'Итого' %}:</strong>
                <span class="Cart-price">{{ cart.get_total_price }}</span>
                {% if user.cart.discount %}
                  <span class="Cart-price_old">{{ cart.total_price_old }}</span>
                {% endif %}
              </div>
              <div class="Cart-block"><a class="btn btn_success btn_lg" href="{% url 'order-step-one' %}">{% trans 'Оформить заказ' %}</a>
              </div>
            </div>
          </form>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

templates/catalog.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'Каталог' %}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item">
              <a href="main_page.html">{% translate 'Главная страница' %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current">
              <span>{% translate 'Каталог' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Фильтр' %}</strong>
            </header>
            <div class="Section-columnContent">
              <form class="form" method="get">
                <div class="form-group">
                  <div class="range Section-columnRange">
                    <input class="range-line" id="price" name="price" type="text" data-type="double" data-min="50"
                           data-max="5000" data-from="7" data-to="27"/>
                    <div class="range-price">Price:&#32;
                      <div class="rangePrice">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <input class="form-input form-input_full" id="title" name="title" type="text" placeholder="{% translate 'Название' %}"/>
                </div>
                <div class="form-group">
                  <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->
                  <select class="form-select" name="seller">
                    <option value="seller" selected="selected" disabled="disabled">
                      {% translate 'Продавец' %}
                    </option>
                    {% for seller in sellers %}
                      <option value="{{ seller.id }}">
                        {{ seller.name }}
                      </option>
                    {% endfor %}

                  </select>
                </div>
                <div class="form-group">
                  <label class="toggle">
                    <input type="checkbox" name="is_exist"/>
                    <span class="toggle-box"></span><span class="toggle-text">{% translate 'Только товары в наличии' %}</span>
                  </label>
                </div>
                <div class="form-group">
                  <label class="toggle">
                    <input type="checkbox" name="free_delivery"/>
                    <span class="toggle-box"></span><span class="toggle-text">{% translate 'С бесплатной доставкой' %}</span>
                  </label>
                </div>
                <div class="form-group">
                  <div class="buttons">
                    <button class="btn btn_square btn_dark btn_narrow">{% translate 'Фильтр' %}</button>
{#                    <a class="btn btn_square btn_dark btn_narrow" href="#">{% translate 'Фильтр' %}</a>#}
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Популярные теги' %}</strong>
            </header>
            <div class="Section-columnContent">
              {% if popular_tags %}
                <div class="buttons">
                  {% for tag in popular_tags %}
                    <a class="btn btn_default btn_sm" href="#">{{ tag.name }}</a>  {# ссылка на тег? #}
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Sort">
            <div class="Sort-title">
              {% translate 'Сортировать по' %}:
            </div>
            <div class="Sort-variants">
              <a class="Sort-sortBy Sort-sortBy_dec" href="
              {% if category_slug %}
                {% url 'catalog_category_order_by_views' category_slug %}
              {% else %}
                {% url 'catalog_order_by_views' %}
              {% endif %}
              ">{% translate 'Популярности' %}</a>

              <a class="Sort-sortBy" href="
              {% if category_slug %}
                {% url 'catalog_category_order_by_price' category_slug %}
               {% else %}
                {% url 'catalog_order_by_price' %}
              {% endif %}">{% translate 'Цене' %}</a>


              <a class="Sort-sortBy" href="
              {% if category_slug %}
                {% url 'catalog_category_order_by_rating' category_slug %}
              {% else %}
                {% url 'catalog_order_by_rating' %}
              {% endif %}
              ">{% translate 'Отзывам' %}</a>

              <a class="Sort-sortBy Sort-sortBy_inc" href="
              {% if category_slug %}
                {% url 'catalog_category_order_by_date' category_slug %}
              {% else %}
                {% url 'catalog_order_by_date' %}
              {% endif %}
              ">{% translate 'Новизне' %}</a> {# ссылки сортировки #}
            </div>
          </div>
          <div class="Cards">
            {% for product in products %}
              <div class="Card
                  {% if forloop.counter > 4 %} hide_md {% endif %}
                  {% if forloop.counter > 6 %} hide_1450 {% endif %}">

                <a class="Card-picture" href="">
                  <img src="{{ product.images.all.0 }}" alt="card.jpg"/>
                </a>
                <div class="Card-content">
                  <strong class="Card-title">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                  </strong>
                  <div class="Card-description">
                    <div class="Card-cost">
                      {% if product.old_price %}
                        <span class="Card-priceOld">{{ product.old_price }}</span>
                      {% endif %}
                      <span class="Card-price">{{ product.price }}</span>
                    </div>
                    <div class="Card-category">{{ product.category }}
                    </div>
                    <div class="Card-hover">
                      <a class="Card-btn" href="{{ product.get_absolute_url }}">
                        <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>
                      </a>
                      <a class="Card-btn" href="{% url 'cart:random_add' product.pk %}">
                        <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                      </a>
                      <a class="Card-btn" href="{% url 'add_to_compare' product.pk %}">
                        <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
                      </a>
                    </div>
                  </div>
                </div>
                {% if product.discount %}
                  <div class="Card-sale">-{{ product.discount }}%
                  </div>
                {% endif %}
              </div>
            {% endfor %}
          </div>
          {% block pagination %}
            {% include 'inc/blocks/pagination.html' %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}