cart/urls.py
from django.urls import path
from .views import cart_add, CartView, cart_remove, change_count


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_pk>/', cart_add, name='random_add'),
    path('add/<int:product_pk>/<int:shop_product_pk>/', cart_add, name='add'),
    path('change/<int:shop_product_pk>/<str:quantity>/', change_count, name='change'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

users/urls.py
from django.urls import path

from users.views import register_view, LogOutView, reset_password, user_login, HistoryView, history_remove

app_name = 'users'


urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('password_reset/', reset_password, name='reset_password'),
    path("history/", HistoryView.as_view(), name='view_history'),
    path("history/remove/<int:pk>", history_remove, name='history_remove')
]

shop/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from product.models import Product
from users.models import CustomUser


class Shop(models.Model):
    """Магазин"""

    name = models.CharField(max_length=512, verbose_name=_("название"))
    holder = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="shops", verbose_name=_("владелец"))
    address = models.TextField(blank=True, null=True, verbose_name=_("адрес"))
    email = models.EmailField(blank=True, null=True, verbose_name=_("почта"))
    validator_phone = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message=' '.join([str(_('Телефон должен быть введён в формате:')), '+777777777777',
                          str(_('Максимально количество цифр - 15'))]))
    phone = models.CharField(max_length=16, blank=True, validators=[validator_phone], null=True, verbose_name=_("телефон"))
    description = models.TextField(blank=True, null=True, verbose_name=_("описание"))
    logo = models.ImageField(upload_to="logo", null=True, verbose_name=_("логотип"))
    slug = models.SlugField(unique=True, verbose_name=_("слаг"))

    def __str__(self):
        return f"Магазин {self.name}"

    class Meta:
        verbose_name = _("магазин")
        verbose_name_plural = _("магазины")


class ShopProduct(models.Model):
    """Модель продукта магазина"""

    store = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name="shop_products", verbose_name=_("магазин"))
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="shop_products", verbose_name=_("продукт")
    )
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("цена"))
    old_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("старая цена"))
    amount = models.IntegerField(default=0, verbose_name=_("количество"))
    add_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата добавления"))

    def __str__(self):
        return f"Продукт {self.product} из магазина {self.store}"

    class Meta:

        verbose_name = _('Продукт магазина')
        verbose_name_plural = _('Продукты магазина')

users/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


def update_avatar(instance, filename):
    path = "avatars/"
    file_name = f'{instance.user.email}_avatar.{filename.split(".")[-1]}'
    return os.path.join(path, file_name)


class CustomUser(AbstractUser):
    """Модель кастомного пользователя"""
    username = None
    email = models.EmailField(verbose_name=_('электронная почта'), max_length=128, unique=True)
    validator_phone = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message=' '.join([str(_('Телефон должен быть введён в формате:')), '+777777777777',
                          str(_('Максимально количество цифр - 15'))]))
    phone_number = models.CharField(verbose_name=_('телефон'), validators=[validator_phone], max_length=16, blank=True)
    full_name = models.CharField(verbose_name=_('ФИО'), max_length=256, blank=True)
    # avatar = models.ImageField(verbose_name=_('аватар'), upload_to=update_avatar)
    avatar = models.ImageField(verbose_name=_('аватар'), upload_to="users")
    is_staff = models.BooleanField(verbose_name=_('работник'), default=False)
    is_active = models.BooleanField(verbose_name=_('флаг активности'), default=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name = _('пользователь')
        verbose_name_plural = _('пользователи')

        permissions = (
            ('can_do_order', _('Может делать заказ')),
        )

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'password', 'phone_number', 'full_name', 'avatar', )


class ResetPasswordForm(forms.Form):

    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data['email']

        try:
            CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            raise ValidationError(message=_('Пользователь не найден'))

        return email


class LogInForm(forms.Form):
    """Форма для авторизации"""
    email = forms.EmailField()
    password = forms.CharField(label=_('Пароль'), widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()

        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        user = authenticate(email=email, password=password)

        if user is None:
            raise ValidationError(message=_('Не найдено пары E-mail/пароль'))

        return user

users/views.py
from django.views import View
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.views import LogoutView

from personal_account.models import ViewsHistory
from personal_account.services import PersonalAccount
from users.forms import CustomUserCreationForm, ResetPasswordForm, LogInForm

from .services import register_user, password_change, login_user


def register_view(request):
    """Представление с регистрацией пользователя"""
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            register_user(request, user_form=form)

            return redirect(to='main_page')

    return render(request, template_name='users/register.html', context={'form': form})


def user_login(request):
    """Представление с авторизацией пользователя"""
    form = LogInForm()

    if request.method == 'POST':
        form = LogInForm(request.POST)

        if form.is_valid():
            login_user(request, form)

            return redirect(to='main_page')

    return render(request, 'users/login.html', {'form': form})


class LogOutView(LogoutView):
    template_name = 'users/logout.html'


def reset_password(request):
    """Представление с регистрацией пользователя"""
    form = ResetPasswordForm()

    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)

        if form.is_valid():
            password_change(request, user_form=form)
            # Здесь будет редирект на главную
            return HttpResponse('Заглушка.'
                                'Ваш новый пароль qwerty1234.')

    return render(request, template_name='users/reset_password.html', context={'form': form})


class HistoryView(View):
    def get(self, request):
        viewed_products = PersonalAccount.get_last_viewed(request.user.id)
        context = {
            'viewed_products': viewed_products
        }
        return render(request, 'users/view_history.html', context)


def history_remove(request, pk: int):
    """Представление удаления товара из списка просмотренных"""
    PersonalAccount.delete_viewed_product(request.user.id, int(pk))
    return redirect(to='users:view_history')

templates/users/account.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main%}
<div class="Middle Middle_top">
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">{% translate 'Личный кабинет' %}</h1>
        <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
          </li>
          <li class="breadcrumbs-item breadcrumbs-item_current">
            <span>{% translate 'Личный кабинет' %}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="Section Section_column Section_columnLeft">
    <div class="wrap">
      <div class="Section-column">
        <div class="Section-columnSection">
          <header class="Section-header">
            <strong class="Section-title">{% translate 'Меню' %}</strong>
          </header>
          <div class="Section-columnContent sticky">
            <div class="NavigateProfile">
              <ul class="menu menu_vt">
                <li class="menu-item_ACTIVE menu-item">
                  <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="{% url 'profile' %}">{% translate 'Профиль' %}</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
                </li>
                  <li class="menu-item menu-item">
                      <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
                  </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="Section-content">
        <header class="Section-header margin">
          <h2 class="Section-title">{% translate 'Ваш профиль' %}</h2>
        </header>
        <div class="Account">
          <div class="Account-group">
              <div> <img style="width: 250px;
                                border-radius: 5px;
                                border: 1px solid black;
                                padding: 3px;
                                background-color: whitesmoke;
                                margin-right: 10px"
                         src="
                                {% if request.user.avatar %}
                                {{ request.user.avatar.url }}
                                {% else %}
                                http://www.rosphoto.com/images/u/articles/1510/7_5.jpg
                                {% endif %}">
              </div>
            <div class="Account-column">
            {% if request.user.full_name %}
              <div class="Account-name">{{ request.user.full_name }}</div>
            {% else %}
              <div class="Account-name">{{ request.user.email }}</div>
            {% endif %}
            <a class="Account-editLink" href="{% url 'profile' %}">{% translate 'Изменить профиль' %}</a>
            </div>
          </div>
          <div class="Account-group">
            <div class="Account-column Account-column_full">
              <header class="Section-header">
                <h2 class="Section-title">{% translate 'История заказов' %}</h2>
              </header>
              <div class="Cards Cards_account" style="position: relative">
                  {% if last_order.order_in %}
                <a type="button" class="btn__show-history" href="#">{% translate 'Посмотреть последний заказ' %}</a>
                <div class="Orders historyOrder">
                  <div class="Order Order_anons">
                    <div class="Order-personal">
                      <div class="row">
                        <div class="row-block">
                          <a class="Order-title" href="{{ last_order.get_absolute_url }}">
                              Заказ&#32;<span class="Order-numberOrder">{{ last_order.id }}</span>
                              &#32;от&#32;<span class="Order-dateOrder">{{ last_order.ordered }}</span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div style="text-align: center">
                    <a type="button" class="btn__close">{% translate 'свернуть' %}</a>
                  </div>
                </div>
                  {% else %}
                  <h2>{% translate 'Вы ещё ничего не заказывали' %}</h2>
                  {% endif %}
              </div>
            </div>
          </div>
          <div class="Account-group">
              <div class="Account-column Account-column_full">
                <header class="Section-header">
                  <h2 class="Section-title">{% translate 'История просмотров' %}</h2>
                </header>
                {% if user.viewshistorys %}
                  <div class="Cards Cards_account">
                    {% for product in user.viewshistorys %}
                      <div class="Card
                        {% if forloop.counter == 2 %}hide_700{% endif %}
                        {% if forloop.counter == 3 %}hide_md{% endif %} ">
                        <a class="Card-picture" href="#"><img src="{{ product.image }}" alt="card.jpg"/></a>
                        <div class="Card-content">
                          <strong class="Card-title"><a href="#">{{ product.name }}</a></strong>
                          <div class="Card-description">
                            <div class="Card-cost">
                              {% if product.old_price %}
                                <span class="Card-priceOld">{{ product.old_price }}</span>
                              {% endif %}
                              <span class="Card-price">{{ product.price }}</span>
                            </div>
                            <div class="Card-category">{{ product.category }}
                            </div>
                            <div class="Card-hover">
                              <a class="Card-btn" href="{% url 'product' product.slug %}">
                                <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>
                              </a>
                              <a class="Card-btn" href="{% url 'cart_add' product.id %}">
                                <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                              </a>
                              <a class="Card-btn" href="{% url 'compare' product.id %}">
                                <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
                              </a>
                            </div>
                          </div>
                        </div>
                        {% if product.discount %}
                          <div class="Card-sale">-{{ product.discount }}%</div>
                        {% endif %}
                      </div>
                    {% endfor %}
                  </div>
                  <div class="Account-editLink Account-editLink_view">
                    <a href="{% url 'users:view_history' %}">{% translate 'Перейти на полный список' %}</a>
                  </div>
                {% else %}
                    <h2 style="text-align: center">{% translate 'Ваша история просмотров пока пуста' %}</h2>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <div style="margin: 30px auto">
        {% if user.is_authenticated %}
            <h3>{% trans 'Вы уже авторизованы на сайте' %}</h3>
        {% else %}
            <h3>{% translate 'Нет аккаунта' %}? <a href="{% url 'users:register' %}">{% trans 'Регистрация' %}</a></h3>
            <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans 'Войти' %}</button>
            <h4><a href="{% url 'users:reset_password' %}">{% trans 'Забыли пароль?' %}</a></h4>
        </form>
        {% endif %}
    </div>
{% endblock %}

templates/users/logout.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <div style="margin: 30px auto">
        <h2>{% trans 'Вы вышли из системы' %}</h2>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main%}

<div class="Middle-top">
  <div class="wrap">
    <div class="Middle-header">
      <h1 class="Middle-title">{% translate 'Профиль' %}</h1>
      <ul class="breadcrumbs Middle-breadcrumbs">
        <li class="breadcrumbs-item">
          <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
        </li>
        <li class="breadcrumbs-item breadcrumbs-item_current">
          <span>{% translate 'Профиль' %}</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="Section Section_column">
  <div class="wrap">
    <div class="Section-column">
      <div class="Section-columnSection sticky margin__menu-right">
        <header class="Section-header">
          <strong class="Section-title">{% translate 'Меню'%}</strong>
        </header>
        <div class="Section-columnContent">
          <div class="NavigateProfile">
            <ul class="menu menu_vt">
              <li class="menu-item">
                  <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
              </li>
              <li class="menu-item">
                  <a class="menu-link_ACTIVE" href="{% url 'account' %}">{% translate 'Профиль' %}</a>
              </li>
              <li class="menu-item">
                  <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
              </li>
              <li class="menu-item">
                  <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
              </li>
              <li class="menu-item menu-item">
                  <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="Section-content">
      <header class="Section-header margin">
        <h2 class="Section-title">{% translate 'Ваш профиль' %}</h2>
      </header>
      <div class="Profile">
        <form class="profile__container" method="post" enctype="multipart/form-data">
             {% csrf_token %}
          <div class="profile__left">
              <div class="form-group">
                                <label class="form-label" for="avatar">{% trans 'Аватар' %}</label>
                                {% if request.user.avatar %}
                                <div style="border-radius: 25px" class="Profile-avatar">
                                {% else %}
                                <div style="border-radius: 25px" class="Profile-avatar Profile-avatar_noimg" >
                                {% endif %}
                                    <div style="border-radius: 25px" class="Profile-img">
                                        {%  if request.user.avatar %}
                                            <img src="{{ request.user.avatar.url}}" alt="#.png">
                                        {% else %}
                                            <img src="assets/img/#.png" alt="#.png">
                                        {% endif %}
                                    </div>
                                    <span class="avatar-span">{% trans 'Выбрать/Изменить' %}</span>
                                    <input class="Profile-file form-input" id="avatar" accept="image/*" name="avatar" type="file" data-validate="onlyImgAvatar">
                                    <span>{{ form.errors.avatar }}</span>
                                </div>
                            </div>
            <div class="profile__form">
              <label class="form-label" for="full_name">{% translate 'ФИО' %}</label>
              <input
                      value="{{ request.user.full_name }}"
                class="form-input profile__border"
                id="full_name"
                name="full_name"
                placeholder="ФИО"
                type="text"
              />
                <span>{{ form.errors.full_name }}</span>
            </div>
          </div>
          <div class="profile__right">
            <div class="profile__form-telephone">
              <label class="form-label" for="id_phone">{% translate 'Телефон' %}</label>
              <input
                      value="{{ request.user.phone_number }}"
                class="form-input profile__border"
                placeholder="Телефон"
                name="phone_number"
                required
                type="text"
              />
                <span>{{ form.errors.phone_number }}</span>
            </div>

              <label class="form-label" for="id_phone">{% translate 'Почта' %}</label>
              <input
                      value="{{ request.user.email }}"
                class="form-input profile__border"
                placeholder="Почта"
                name="email"
                required
                type="text"
              />
              <span>{{ form.errors.email }}</span>
            </div>
          <div>
            <button class="btn btn_success" type="submit">{% translate 'Изменить' %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <div style="margin: 30px auto">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans 'Регистрация' %}</button>
        </form>
    </div>
{% endblock %}

templates/users/reset_password.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
    <div style="margin: 30px auto">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% trans 'Восстановить пароль' %}</button>
        </form>
    </div>
{% endblock %}

templates/users/view_history.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% translate 'История просмотров' %}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item">
              <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current">
                <span>{% translate 'История просмотров' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% translate 'Меню' %}</strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item">
                      <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
                  </li>
                  <li class="menu-item">
                      <a class="menu-link" href="{% url 'profile' %}">{% translate 'Профиль' %}</a>
                  </li>
                  <li class=" menu-item">
                      <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item">
                      <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <header class="Section-header margin">
            <h2 class="Section-title">{% translate 'Ваша история просмотров' %}</h2>
          </header>
          {% if viewed_products %}
            <div class="Cards">
              {% for product in viewed_products %}
              <div class="Card{% if forloop.counter > 18 %} hide_1450 {% endif %}">
                <a class="Card-picture" href="{% url 'product' product.product.slug %}">
                  <img src="{{ product.image }}" alt="card.jpg"/>
                </a>
                <div class="Card-content">
                  <strong class="Card-title"><a href="#">{{ product.product.name }}</a></strong>
                  <div class="Card-description">
                    <div class="Card-cost">
                      {% if product.old_price %}
                        <span class="Card-priceOld">{{ product.product.old_price }}</span>
                      {% endif %}
                      <span class="Card-price">{{ product.product.price }}</span>
                    </div>
                    <div class="Card-category">{{ product.product.category }}
                    </div>
                    <div class="Card-hover">
                      <a class="Card-btn" href="{% url 'product' product.product.slug %}">
                        <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>
                      </a>
                      <a class="Card-btn" href="{% url 'cart:random_add' product.product.id %}">
                        <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                      </a>
                      <a class="Card-btn" href="{% url 'add_to_compare' product.product.id %}">
                        <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
                      </a>
                      <a class="Card-btn" href="{% url 'users:history_remove' product.product.id %}">
                          <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/>
                      </a>
                    </div>
                  </div>
                </div>
                {% if product.product.discount %}
                  <div class="Card-sale">{{ product.product.discount }}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            </div>
          {% else %}
            <p>Вы пока ничего не смотрели</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>



{% endblock %}