cart/urls.py
from django.urls import path
from .views import cart_add, CartView, cart_remove, change_count


app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_pk>/', cart_add, name='random_add'),
    path('add/<int:product_pk>/<int:shop_product_pk>/', cart_add, name='add'),
    path('change/<int:shop_product_pk>/<str:quantity>/', change_count, name='change'),
    path('remove/<int:pk>/', cart_remove, name='remove'),
]

shop/urls.py
from django.urls import path
from .views import (
    ShopAllView,
    ShopDetailView,
    CreateShopView,
    AddGoodView,
    EditShopView,
    EditGoodView,
    ShopRoomView,
    ShopRoomDetailView,
)

urlpatterns = [
    path("", ShopAllView.as_view(), name="shops"),
    path("<int:shop_pk>/", ShopDetailView.as_view(), name="shop"),
    path("create/shop/", CreateShopView.as_view(), name="create-shop"),
    path("create/good/", AddGoodView.as_view(), name="create-good"),
    path("edit/shop/<int:shop_pk>/", EditShopView.as_view(), name="edit-shop"),
    path("edit/good/<int:good_pk>", EditGoodView.as_view(), name="edit-good"),
    path("seller-room/", ShopRoomView.as_view(), name="seller-room"),
    path("seller-room/shop/<int:shop_pk>/", ShopRoomDetailView.as_view(), name="seller-shop"),
]

users/urls.py
from django.urls import path

from users.views import register_view, LogOutView, reset_password, user_login, HistoryView, history_remove

app_name = 'users'


urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('password_reset/', reset_password, name='reset_password'),
    path("history/", HistoryView.as_view(), name='view_history'),
    path("history/remove/<int:pk>", history_remove, name='history_remove')
]

shop/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from product.models import Product
from users.models import CustomUser


class Shop(models.Model):
    """Магазин"""

    name = models.CharField(max_length=512, verbose_name=_("название"))
    holder = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="shops", verbose_name=_("владелец"))
    address = models.TextField(blank=True, null=True, verbose_name=_("адрес"))
    email = models.EmailField(blank=True, null=True, verbose_name=_("почта"))
    validator_phone = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message=' '.join([str(_('Телефон должен быть введён в формате:')), '+777777777777',
                          str(_('Максимально количество цифр - 15'))]))
    phone = models.CharField(max_length=16, blank=True, validators=[validator_phone], null=True, verbose_name=_("телефон"))
    description = models.TextField(blank=True, null=True, verbose_name=_("описание"))
    logo = models.ImageField(upload_to="logo", null=True, verbose_name=_("логотип"))
    slug = models.SlugField(unique=True, verbose_name=_("слаг"))

    def __str__(self):
        return f"Магазин {self.name}"

    class Meta:
        verbose_name = _("магазин")
        verbose_name_plural = _("магазины")


class ShopProduct(models.Model):
    """Модель продукта магазина"""

    store = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name="shop_products", verbose_name=_("магазин"))
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="shop_products", verbose_name=_("продукт")
    )
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("цена"))
    old_price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_("старая цена"))
    amount = models.IntegerField(default=0, verbose_name=_("количество"))
    add_at = models.DateTimeField(auto_now_add=True, verbose_name=_("дата добавления"))

    def __str__(self):
        return f"Продукт {self.product} из магазина {self.store}"

    class Meta:

        verbose_name = _('Продукт магазина')
        verbose_name_plural = _('Продукты магазина')

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    """Форма для добавления товара в корзину"""
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'Amount-input form-input', 'value': 1}))

    def clean_quantity(self):
        """Функция проверяет, что поле является числом"""
        data = self.cleaned_data['quantity']
        try:
            data = int(data)
            return data
        except ValueError:
            pass

shop/forms.py
from django import forms
from .models import Shop, ShopProduct


class CreateShop(forms.ModelForm):
    class Meta:
        model = Shop
        fields = "__all__"


class AddProductToTheShop(forms.ModelForm):
    class Meta:
        model = ShopProduct
        fields = "__all__"


class EditShop(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ("name", "address", "email", "phone", "logo")


class EditProductInTheShop(forms.ModelForm):
    class Meta:
        model = ShopProduct
        fields = ("old_price", "price", "amount")

shop/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, View
from config.settings.base import SHOPS_VIEW
from .services import ShopServices
from .models import Shop, ShopProduct
from .forms import CreateShop, AddProductToTheShop, EditShop, EditProductInTheShop


# Create your views here.


class ShopAllView(ShopServices, ListView):
    model = Shop
    template_name = "inc/shop/shops.html"
    paginate_by = SHOPS_VIEW
    context_object_name = "shops"

    def get_queryset(self):
        return self.get_all_shops()


class ShopDetailView(DetailView):
    model = Shop
    template_name = "inc/shop/shop_info.html"
    context_object_name = "shop"
    pk_url_kwarg = "shop_pk"
    paginate_by = SHOPS_VIEW


class ShopRoomView(ShopServices, ListView):
    model = Shop
    template_name = "inc/shop/seller_home.html"
    context_object_name = "shops"
    paginate_by = SHOPS_VIEW

    def get_queryset(self):
        return self.get_user_shop(user=self.request.user)


class ShopRoomDetailView(DetailView):
    model = Shop
    template_name = "inc/shop/seller_shop.html"
    context_object_name = "shop"
    pk_url_kwarg = "shop_pk"
    paginate_by = SHOPS_VIEW


class CreateShopView(ShopServices, View):
    template_name = "inc/shop/create_shop.html"

    def get(self, request):
        form = CreateShop()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = CreateShop(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("seller-room")
        return render(request, self.template_name, {"form": form})


class AddGoodView(ShopServices, View):
    template_name = "inc/shop/create_good.html"

    def get(self, request):
        context = {
            "goods": self.get_all_goods(),
            "shops": self.get_user_shop(user=request.user),
            "form": AddProductToTheShop(),
        }
        return render(request, self.template_name, context=context)

    def post(self, request):
        form = AddProductToTheShop(request.POST)
        if form.is_valid():
            form.save()
            return redirect("seller-room")
        return render(request, self.template_name, {"form": form})


class EditShopView(ShopServices, DetailView):
    context_object_name = "shop"
    model = Shop
    template_name = "inc/shop/edit_shop.html"
    pk_url_kwarg = "shop_pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = EditShop(instance=self.get_object())
        return context

    def post(self, request, shop_pk):
        form = EditShop(request.POST, request.FILES, instance=self.get_object())
        if form.is_valid():
            form.save()
            return redirect("seller-room")
        return redirect(reverse("edit-shop", kwargs={"shop_pk": shop_pk}))


class EditGoodView(ShopServices, DetailView):
    context_object_name = "good"
    template_name = "inc/shop/edit_good.html"
    model = ShopProduct
    pk_url_kwarg = "good_pk"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["form"] = EditProductInTheShop(instance=self.get_object())
        return context

    def post(self, request, good_pk):
        form = EditProductInTheShop(request.POST, request.FILES, instance=self.get_object())
        if form.is_valid():
            form.save()
            return redirect("seller-room")
        return redirect(reverse("edit-shop", kwargs={"good_pk": good_pk}))

templates/inc/shop/create_good.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main%}
<div class="Middle-top">
  <div class="wrap">
    <div class="Middle-header">
      <h1 class="Middle-title">{% translate 'Добавление товара' %}</h1>
      <ul class="breadcrumbs Middle-breadcrumbs">
        <li class="breadcrumbs-item">
          <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
        </li>
        <li class="breadcrumbs-item breadcrumbs-item_current">
          <span>{% translate 'Комната продавца' %}</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="Section Section_column Section_columnLeft">
  <div class="wrap">
    <div class="Section-column">
      <div class="Section-columnSection sticky">
        <header class="Section-header">
          <strong class="Section-title">{% translate 'Меню' %}</strong>
        </header>
        <div class="Section-columnContent">
          <div class="NavigateProfile">
            <ul class="menu menu_vt">
              <li class="menu-item">
                <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'profile' %}">{% translate 'Профиль' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
              </li>
              <li class="menu-item_ACTIVE menu-item">
                <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="Section-content">
      <header class="Section-header margin">
        <h2 class="Section-title">{% translate 'Добавление товара в магазин' %}</h2>
      </header>
      <div class="Profile">
              <form class="form Profile-form" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row">
                      <div class="row-block">
                          <div class="form-group require-field">
                              <label class="form-label" for="id_seller">{% trans 'Выберите магазин' %}</label>
                              <select style="width: 40% !important;" class="border size_custom" name="store" required="" id="id_seller">
                                  <option value="" selected="">---------------------------</option>
                              {% if shops %}
                                  {% for store in shops %}
                                  <option value="{{ store.id }}">{{ store.name }}</option>
                                  {% endfor %}
                              {% else %}
                              <option value="Нет магазинов">{% trans 'Нет магазинов' %}</option>
                              {% endif %}
                              </select>
                          </div>
                      <div class="form-group require-field">
                              <label class="form-label" for="id_seller">{% trans 'Выберите продукт' %}</label>
                              <select style="width: 40% !important;" class="border size_custom" name="product" required="" id="id_seller">
                                  <option value="" selected="">---------------------------</option>
                                  {% if goods %}
                                  {% for good in goods %}
                                  <option value="{{ good.id }}">{{ good.name }}</option>
                                  {% endfor %}
                              {% else %}
                              <option value="Нет товаров">{% trans 'Нет товаров' %}</option>
                              {% endif %}
                              </select>
                          </div>

                      </div>
                  </div>
                  <div class="row">
                      <div class="row-block">
                          <div class="form-group">
                              <label class="form-label" for="id_quantity">{% trans 'Количество' %}:
                              </label>
                              <input style="width: 40% !important;" class="border size_custom form-input" type="number" name="amount" required id="id_quantity">
                              <span>{{ form.errors.amount }}</span>
                          </div>
                          <div class="form-group">
                              <label class="form-label" for="id_price">{% trans 'Цена' %}:</label>
                              <input style="width: 40% !important;" class="border size_custom form-input" id="id_price" name="price" type="number" required step="0.01">
                              <span>{{ form.errors.price }}</span>
                          </div>
                          <div class="form-group">
                              <label class="form-label" for="id_price">{% trans 'Старая цена' %}:</label>
                              <input style="width: 40% !important;" class="border size_custom form-input" id="id_price" name="old_price" type="number" required step="0.01">
                              <span>{{ form.errors.old_price }}</span>
                          </div>
                      </div>
                  </div>
                    <div style="width: 40% !important;" class="Profile-btn">
                    <button class="btn btn_reset" type="reset">{% translate 'Отменить' %}</button>
                    <button class="btn btn_success" type="submit">{% translate 'Создать' %}</button>
                    </div>
                </div>
              </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/inc/shop/create_shop.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main %}

<div class="Middle-top">
  <div class="wrap">
    <div class="Middle-header">
      <h1 class="Middle-title">{% translate 'Создание магазина' %}</h1>
      <ul class="breadcrumbs Middle-breadcrumbs">
        <li class="breadcrumbs-item">
          <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
        </li>
        <li class="breadcrumbs-item breadcrumbs-item_current">
          <span>{% translate 'Комната продавца' %}</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="Section Section_column Section_columnLeft">
  <div class="wrap">
    <div class="Section-column">
      <div class="Section-columnSection sticky">
        <header class="Section-header">
          <strong class="Section-title">{% translate 'Меню' %}</strong>
        </header>
        <div class="Section-columnContent">
          <div class="NavigateProfile">
            <ul class="menu menu_vt">
              <li class="menu-item">
                <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'account' %}">{% translate 'Профиль' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
              </li>
              <li class="menu-item_ACTIVE menu-item">
                <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="Section-content">
      <form
        class="block__create-store-form"
        method="post"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="block__create-store-left">
            <input class="form-input" name="holder"
                                 value="{{ request.user.id }}"
                                 type="hidden">
          <div class="form-group">
            <label class="form-label" for="id_name">{% translate 'Название магазина' %}</label>
            <input
              class="form-input border"
              id="id_name"
              required
              name="name"
              type="text"
              placeholder="{% translate 'Введите название' %}"
            />
              <span>{{ form.errors.name }}</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="id_address">{% translate 'Адрес' %}</label>
            <textarea
              class="border"
              name="address"
              cols="10"
              rows="4"
              required
              maxlength="255"
              id="id_address"
              placeholder="{% translate 'Введите адрес' %}"
            ></textarea>
              <span>{{ form.errors.address }}</span>
          </div>

          <div class="form-group">
            <label class="form-label" for="id_phone">{% translate 'Телефон' %}</label>
            <input
              class="form-input border"
              id="id_phone"
              required
              name="phone"
              type="text"
              placeholder="{% translate 'Введите телефон' %}"
            />
              <span>{{ form.errors.phone }}</span>
          </div>
          <div class="form-group form__email">
            <label class="form-label" for="id_email">{% translate 'Почта' %}</label>
            <input
              class="form-input border"
              id="id_email"
              required
              name="email"
              type="email"
              placeholder="{% translate 'Введите почту' %}"
            />
              <span>{{ form.errors.email }}</span>
          </div>
        </div>
        <div class="block__create-store-right">
          <div class="form-group">
            <label class="form-label" for="id_description">{% translate 'Описание' %}</label>
            <textarea
              class="border"
              name="description"
              cols="25"
              rows="13"
              maxlength="255"
              id="id_description"
              placeholder="{% translate 'Описание' %}"
            ></textarea>
              <span>{{ form.errors.description }}</span>
          </div>
            <div class="form-group">
                <label class="form-label" for="url_shop">{% translate 'Слаг' %}</label>
                <input
                  class="form-input border"
                  id="url_shop"
                  required
                  name="slug"
                  type="text"
                  placeholder="{% translate 'Введите слаг' %}"
                />
                <span>{{ form.errors.slug }}</span>
            </div>
            <div class="form-group">
              <label class="form-label" for="avatar">{% trans 'Выберите лого' %}</label>
              {% if shop.logo %}
                  <div style="border-radius: 25px" class="Profile-avatar">
              {% else %}
                  <div style="border-radius: 25px" class="Profile-avatar Profile-avatar_noimg" >
              {% endif %}
              <div class="Profile-img">
                  {%  if shop.logo %}
                      <img src="{{ shop.logo.url }}" alt="#.png">
                  {% else %}
                      <img src="assets/img/#.png" alt="#.png">
                  {% endif %}
              </div>
                <span class="avatar-span">{% trans 'Выбрать/Изменить' %}</span>
                <input class="Profile-file form-input border" id="avatar" accept="image/*" name="logo" type="file" data-validate="onlyImgAvatar">
              </div>
                </div>
                <div class="form-group">
                    <div class="Profile-btn">
                        <button class="btn btn_reset" type="reset">{% translate 'Отменить' %}</button>
                        <button class="btn btn_success" type="submit">{% translate 'Создать' %}</button>
                    </div>
                </div>
            </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/inc/shop/edit_good.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main%}
<div class="Middle-top">
  <div class="wrap">
    <div class="Middle-header">
      <h1 class="Middle-title">{% translate 'Изменение товара' %}</h1>
      <ul class="breadcrumbs Middle-breadcrumbs">
        <li class="breadcrumbs-item">
          <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
        </li>
        <li class="breadcrumbs-item breadcrumbs-item_current">
          <span>{% translate 'Комната продавца' %}</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="Section Section_column Section_columnLeft">
  <div class="wrap">
    <div class="Section-column">
      <div class="Section-columnSection sticky">
        <header class="Section-header">
          <strong class="Section-title">{% translate 'Меню' %}</strong>
        </header>
        <div class="Section-columnContent">
          <div class="NavigateProfile">
            <ul class="menu menu_vt">
              <li class="menu-item">
                <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'profile' %}">{% translate 'Профиль' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
              </li>
              <li class="menu-item_ACTIVE menu-item">
                <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="Section-content">
      <header class="Section-header margin">
        <h2 class="Section-title">{% translate 'Изменение товара' %}</h2>
      </header>
      <div class="Profile">
       <form
        class="block__create-store-form"
        method="post"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
          <div class="row">
                      <div class="row-block">
                          <div class="form-group">
                              <label class="form-label" for="id_quantity">{% trans 'Количество' %}:
                              </label>
                              <input value="{{ good.amount }}" style="width: 40% !important;" class="border size_custom form-input" type="number" name="amount" required id="id_quantity">
                              <span>{{ form.errors.amount }}</span>
                          </div>
                          <div class="form-group">
                              <label class="form-label" for="id_price">{% trans 'Цена' %} ({{ good.price }}):</label>
                              <input value="{{ good.price }}" style="width: 40% !important;" class="border size_custom form-input" id="id_price" name="price" type="number" required step="0.01">
                              <span>{{ form.errors.price }}</span>
                          </div>
                          <div class="form-group">
                              <label class="form-label" for="id_price">{% trans 'Старая цена' %} ({{ good.old_price }}):</label>
                              <input value="{{ good.old_price }}" style="width: 40% !important;" class="border size_custom form-input" id="id_price" name="old_price" type="number" required step="0.01">
                              <span>{{ form.errors.old_price }}</span>
                          </div>
                           <div style="width: 40% !important;" class="Profile-btn">
                        <button class="btn btn_reset" type="reset">{% translate 'Отменить' %}</button>
                        <button class="btn btn_success" type="submit">{% translate 'Изменить' %}</button>
                    </div>
                      </div>

                  </div>

              </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/inc/shop/edit_shop.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block main %}

<div class="Middle-top">
  <div class="wrap">
    <div class="Middle-header">
      <h1 class="Middle-title">{% translate 'Изменение магазина' %}</h1>
      <ul class="breadcrumbs Middle-breadcrumbs">
          <li class="breadcrumbs-item">
            <a href="{% url 'main_page' %}">{% translate 'Главная страница' %}</a>
          </li>
        <li class="breadcrumbs-item breadcrumbs-item_current">
          <span>{% translate 'Комната продавца' %}</span>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="Section Section_column Section_columnLeft">
  <div class="wrap">
    <div class="Section-column">
      <div class="Section-columnSection sticky">
        <header class="Section-header">
          <strong class="Section-title">{% translate 'Меню' %}</strong>
        </header>
        <div class="Section-columnContent">
          <div class="NavigateProfile">
            <ul class="menu menu_vt">
              <li class="menu-item">
                <a class="menu-link" href="{% url 'account' %}">{% translate 'Личный кабинет' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'profile' %}">{% translate 'Профиль' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'history-order' %}">{% translate 'История заказов' %}</a>
              </li>
              <li class="menu-item">
                <a class="menu-link" href="{% url 'users:view_history' %}">{% translate 'Просмотренные продукты' %}</a>
              </li>
              <li class="menu-item_ACTIVE menu-item">
                <a class="menu-link" href="{% url 'seller-room' %}">{% translate 'Комната продавца' %}</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="Section-content">
      <form
        class="block__create-store-form"
        method="post"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="block__create-store-left">
            <input class="form-input" name="holder"
                                 value="{{ request.user.id }}"
                                 type="hidden">

          <div class="form-group">
            <label class="form-label" for="id_name">{% translate 'Название магазина' %}</label>
            <input
                    value="{{ shop.name }}"
              class="form-input border"
              id="id_name"
              required
              name="name"
              type="text"
              placeholder="{% translate 'Введите название' %}"
            />
              <span>{{ form.errors.name }}</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="id_address">{% translate 'Адрес' %}</label>
            <input
                value="{{ shop.address }}"
                class="form-input border"
              name="address"
              required
              type="text"
              id="id_address"
              placeholder="{% translate 'Введите адрес' %}"
            />
              <span>{{ form.errors.address }}</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="id_phone">{% translate 'Телефон' %}</label>
            <input
                    value="{{ shop.phone }}"
              class="form-input border"
              id="id_phone"
              required
              name="phone"
              type="text"
              placeholder="{% translate 'Введите телефон' %}"
            />
              <span>{{ form.errors.phone }}</span>
          </div>
          <div class="form-group form__email">
            <label class="form-label" for="id_email">{% translate 'Почта' %}</label>
            <input
                    value="{{ shop.email }}"
              class="form-input border"
              id="id_email"
              required
              name="email"
              type="email"
              placeholder="{% translate 'Введите почту' %}"
            />
              <span>{{ form.errors.email }}</span>
          </div>
            <div class="form-group">
                <div class="Profile-btn">
                    <button style="width: 46%!important;" class="btn btn_reset" type="reset">{% translate 'Отменить' %}</button>
                    <button style="width: 46%!important;" class="btn btn_success" type="submit">{% translate 'Изменить' %}</button>
                </div>
            </div>
        </div>
          <div class="form-group">
              <label class="form-label" for="avatar">{% trans 'Avatar' %}</label>
              {% if shop.logo %}
                  <div style="border-radius: 25px" class="Profile-avatar">
              {% else %}
                  <div style="border-radius: 25px" class="Profile-avatar Profile-avatar_noimg" >
              {% endif %}
              <div class="Profile-img">
                  {%  if shop.logo %}
                      <img src="{{ shop.logo.url }}" alt="#.png">
                  {% else %}
                      <img src="assets/img/#.png" alt="#.png">
                  {% endif %}
              </div>
              <span class="avatar-span">{% trans 'Выбрать/Изменить' %}</span>
              <input class="Profile-file form-input border" id="avatar" accept="image/*" name="logo" type="file" data-validate="onlyImgAvatar">
              </div>
              </div>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}